{% set name = "insert-license-header" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/insert_license_header-{{ version }}.tar.gz
  sha256: 5b3202e75ed3bee602e92b9a79642a431a58be1d9f9c79e9af84102d8588e920

build:
  entry_points:
    - insert-license = insert_license_header.insert_license:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - rapidfuzz

test:
  imports:
    - insert_license_header
  commands:
    - pip check
    - insert-license --help
  requires:
    - pip

about:
  home: https://github.com/thomasmarwitz/insert-license-header
  summary: Tool to insert license headers at the beginning of text-based files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thomasmarwitz
