{% set name = "insert-license-header" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/insert_license_header-{{ version }}.tar.gz
  sha256: 0f269ec6cc50a39813600d2abb0b59f392be455da71f712e999dcae608c06c72

build:
  entry_points:
    - insert-license = insert_license_header.insert_license:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - rapidfuzz

test:
  imports:
    - insert_license_header
  commands:
    - pip check
    - insert-license --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thomasmarwitz/insert-license-header
  summary: Tool to insert license headers at the beginning of text-based files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thomasmarwitz
